version: "3.9"

services:
  postgres:
    image: postgres:16          
    container_name: appbarber-db
    restart: always
    environment:
      POSTGRES_USER: admin       
      POSTGRES_PASSWORD: senha123 
      POSTGRES_DB: appbarber     
    ports:
      - "5432:5432"             
    volumes:
      - postgres_data:/var/lib/postgresql/data # mant√©m dados mesmo se o container reiniciar

volumes:
  postgres_data:
